# -*- coding: utf-8 -*-
"""Descriptive Assignment 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3XDCgmCc0MhoSzUPFGFhnnolNxyqIwm

Part A: Importing & **Exploring**
"""

# 1. Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Load the dataset into a DataFrame
# Replace 'your_dataset.csv' with the actual filename or path
df = pd.read_csv('/content/student_performance_large.csv')

# 3. Display the first 5 rows
print("First 5 rows of the dataset:")
print(df.head())

# Display summary statistics
print("\nSummary Statistics:")
print(df.describe(include='all'))

# Display missing value counts
print("\nMissing Value Counts:")
print(df.isnull().sum())

"""Part B: Data **Cleaning**"""

# Handle missing values

# Replace missing StudyHours with the mean
df['StudyHours'].fillna(df['StudyHours'].mean(), inplace=True)

# Replace missing Marks with the median
df['Marks'].fillna(df['Marks'].median(), inplace=True)

# Replace missing Attendance with the column mean
df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

# Verify that missing values are handled
print("\nMissing Value Counts after imputation:")
print(df.isnull().sum())

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Verify the shape after removing duplicates
print("\nShape after removing duplicates:", df.shape)

# Optionally, check again for duplicates
print("Remaining duplicate rows:", df.duplicated().sum())

# 3. Save the cleaned dataset as student_cleaned.csv
df.to_csv('student_cleaned.csv', index=False)

print("Cleaned dataset saved as 'student_cleaned.csv'")

"""Part C: Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns

# Histogram of StudyHours
plt.figure(figsize=(8,6))
sns.histplot(df['StudyHours'], bins=10, kde=True, color='skyblue')

plt.title('Histogram of StudyHours')
plt.xlabel('Study Hours')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Box plot of Marks by Gender
plt.figure(figsize=(8,6))
sns.boxplot(x='Gender', y='Marks', data=df, palette='Set2')

plt.title('Box Plot of Marks by Gender')
plt.xlabel('Gender')
plt.ylabel('Marks')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Scatter plot of StudyHours vs Marks, colored by Gender
plt.figure(figsize=(8,6))
sns.scatterplot(x='StudyHours', y='Marks', hue='Gender', data=df, palette='Set1', s=80)

plt.title('Scatter Plot of StudyHours vs Marks by Gender')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
plt.legend(title='Gender')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Violin plot of Attendance by Gender
plt.figure(figsize=(8,6))
sns.violinplot(x='Gender', y='Attendance', data=df, palette='Pastel1')

plt.title('Violin Plot of Attendance by Gender')
plt.xlabel('Gender')
plt.ylabel('Attendance')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# First style: ggplot
plt.style.use('ggplot')
plt.figure(figsize=(8,6))
sns.scatterplot(x='StudyHours', y='Marks', hue='Gender', data=df, palette='Set1', s=80)
plt.title('Scatter Plot (ggplot style)')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
plt.legend(title='Gender')
plt.show()

# Second style: seaborn-darkgrid
sns.set_style('darkgrid')
plt.figure(figsize=(8,6))
sns.scatterplot(x='StudyHours', y='Marks', hue='Gender', data=df, palette='Set2', s=80)
plt.title('Scatter Plot (seaborn-darkgrid style)')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
plt.legend(title='Gender')
plt.show()

"""Part D: **Insights**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Scatter plot with regression line
plt.figure(figsize=(8,6))
sns.regplot(x='StudyHours', y='Marks', data=df, scatter_kws={'s':70, 'alpha':0.7}, line_kws={'color':'red'})

plt.title('Trend between StudyHours and Marks')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
plt.show()

# Calculate correlation coefficient
corr = df['StudyHours'].corr(df['Marks'])
print(f"Correlation between StudyHours and Marks: {corr:.2f}")

# Calculate average marks by gender
avg_marks_by_gender = df.groupby('Gender')['Marks'].mean()

print("Average Marks by Gender:")
print(avg_marks_by_gender)

# Identify which gender has higher marks
higher_gender = avg_marks_by_gender.idxmax()
print(f"\nOn average, {higher_gender} students score higher marks.")

import matplotlib.pyplot as plt
import seaborn as sns

# Scatter plot with regression line
plt.figure(figsize=(8,6))
sns.regplot(x='Attendance', y='Marks', data=df,
            scatter_kws={'s':70, 'alpha':0.7},
            line_kws={'color':'red'})

plt.title('Relationship between Attendance and Marks')
plt.xlabel('Attendance')
plt.ylabel('Marks')
plt.show()

# Calculate correlation coefficient
corr = df['Attendance'].corr(df['Marks'])
print(f"Correlation between Attendance and Marks: {corr:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Violin plot of Attendance by Gender
plt.figure(figsize=(8,6))
sns.violinplot(x='Gender', y='Attendance', data=df, palette='Pastel1', inner='box')

plt.title('Violin Plot of Attendance by Gender')
plt.xlabel('Gender')
plt.ylabel('Attendance')
plt.show()